# gfortran >= 6 is required
language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
  - 3.6
  - 3.7

os:
  - linux

env: FC=gfortran-6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - gcc-6
      - liblapack-dev
      - libatlas-base-dev

install: pip install -e .[tests]

before_script:
   - cd bin
   - cmake ..
   - cmake --build .

   - ctest -V

   - cd ..

script: 
  - pytest -sv
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

