# gfortran >= 6 is required
language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

env: FC=gfortran-6

group: travis_latest

git:
  depth: 3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - gcc-6
      - liblapack-dev
      - libatlas-base-dev

install: pip install -e .[tests]

before_script:
   - cd bin
   - cmake ..
   - make 

   - make test

   - cd ..

script: pytest -v

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    coverage run ../tests/test_all.py;
    coveralls;
    fi

